name: Deploy view-cart to EC2 (qa)

on:
  push:
    branches:
      - qa

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/view-cart:latest .

    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/view-cart:latest

    - name: SSH & deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          # Instalar Docker si no está
          if ! command -v docker &> /dev/null
          then
            echo "🔧 Installing Docker..."
            sudo apt-get update
            sudo apt-get install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          fi

          # Descargar la nueva imagen desde Docker Hub.
          sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/view-cart:latest

          # Detener y eliminar contenedor anterior si existe
          sudo docker stop view-cart || true
          sudo docker rm view-cart || true

          # Ejecutar contenedor en el puerto 8001
          sudo docker run -d \
            --name view-cart \
            --restart=always \
            -p 8001:8001 \
            ${{ secrets.DOCKERHUB_USERNAME }}/view-cart:latest